### ISSUE TITLE
Allow for starting on port other than 80

### ISSUE THREAD

**Issue by tka85** [awesometic/docker-docusaurus#8]
Perhaps allow to define an alternative port instead of the default `80` via an env variable passed to `docker run`.

```
docker run ... -e PORT=3000
```

**Comment by awesometic** [comment]
Hello.

Thanks for the idea. I can patch to use the custom port number, but I'd like to ask why you are going to set another port number.

I think using the default port number should not affect anything to the other host/Docker services because each container has each IP address. 🤔 
Is there another use case of this?

**Comment by tka85** [comment]
I had misunderstood something. My bad. Request makes no sense. Closing.
